# Use a python module (pydata or seaborn datasets) containing datasets as a source from the iris data. Create a pandas dataframe, df_iris, from this data.

### print the first 3 rows
### print the number of rows and columns (shape)
### print the column names
### print the data type of each column
### print the summary statistics for each of the numeric variables. Would you recommend rescaling the data based on these statistics?

In [1]:
import pandas as pd
import numpy as np
from pydataset import data
import acquire

In [2]:
df_iris = data('iris')

In [3]:
# print the first 3 rows
df_iris.head(3)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa

In [4]:
# print the number of rows and columns (shape)
df_iris.shape

(150, 5)

In [5]:
#print the column names
list(df_iris.columns.values)

['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width', 'Species']

In [6]:
# print the data type of each column
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 1 to 150
Data columns (total 5 columns):
Sepal.Length    150 non-null float64
Sepal.Width     150 non-null float64
Petal.Length    150 non-null float64
Petal.Width     150 non-null float64
Species         150 non-null object
dtypes: float64(4), object(1)
memory usage: 7.0+ KB


In [7]:
# print the summary statistics for each of the numeric variables.
#Would you recommend rescaling the data based on these statistics?

df_iris.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

I don't think scaling is needed

## Read Table1_CustDetails the excel module dataset, Excel_Exercises.xlsx, into a dataframe, df_excel

In [8]:
df_excel = pd.read_excel('Spreadsheets_Exercises.xlsx')

In [9]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7049 entries, 0 to 7048
Data columns (total 12 columns):
customer_id          7049 non-null object
gender               7049 non-null object
is_senior_citizen    7049 non-null int64
partner              7049 non-null object
dependents           7049 non-null object
phone_service        7049 non-null int64
internet_service     7049 non-null int64
contract_type        7049 non-null int64
payment_type         7049 non-null object
monthly_charges      7049 non-null float64
total_charges        7038 non-null float64
churn                7049 non-null object
dtypes: float64(2), int64(4), object(6)
memory usage: 661.0+ KB


In [10]:
# assign the first 100 rows to a new dataframe, df_excel_sample
df_excel_sample = df_excel.iloc[:101,:]

In [11]:
# print the number of rows of your original dataframe
df_excel.shape[0]

7049

In [12]:
df_excel.columns[0]

'customer_id'

In [13]:
# print the first 5 column names
for i in range (0,5): 
    print(df_excel.columns[i])

customer_id
gender
is_senior_citizen
partner
dependents


In [14]:
# print the column names that have a data type of object
mask = df_excel.dtypes == object
df_excel.loc[:,mask].columns

Index(['customer_id', 'gender', 'partner', 'dependents', 'payment_type',
       'churn'],
      dtype='object')

In [29]:
df_excel.columns[df_excel.dtypes == object]

Index(['customer_id', 'gender', 'partner', 'dependents', 'payment_type',
       'churn'],
      dtype='object')

In [15]:
mask = ((df_excel.dtypes == float) | (df_excel.dtypes == int))
df_excel.loc[:,mask].columns

Index(['is_senior_citizen', 'phone_service', 'internet_service',
       'contract_type', 'monthly_charges', 'total_charges'],
      dtype='object')

In [16]:
for i in range (0, len(df_excel.columns)):
     if mask[i] == True:
            print(df_excel.iloc[:,i:i+1].max() - df_excel.iloc[:,i:i+1].min())

is_senior_citizen    1
dtype: int64
phone_service    2
dtype: int64
internet_service    2
dtype: int64
contract_type    2
dtype: int64
monthly_charges    100.5
dtype: float64
total_charges    8666.0
dtype: float64


## 3. Read the data from this google sheet into a dataframe, df_google

In [17]:
sheet_url = 'https://docs.google.com/spreadsheets/d/1Uhtml8KY19LILuZsrDtlsHHDC9wuDGUSe8LTEwvdI5g/edit#gid=341089357'

csv_export_url = sheet_url.replace('/edit#gid=', '/export?format=csv&gid=')

df_google = pd.read_csv(csv_export_url)
df_google.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [18]:
# print the first 3 rows
df_google.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [19]:
# print the number of rows and columns
df_google.shape

(891, 12)

In [20]:
#print the column names
list(df_google.columns)

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [21]:
# print the data type of each column
df_google.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [22]:
# print the summary statistics for each of the numeric variables
df_google.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [23]:
# print the unique values for each of your categorical variables
print(df_google.Survived.unique())
print(df_google.Pclass.unique())
print(df_google.Sex.unique())
print(df_google.SibSp.unique())
print(df_google.Parch.unique())
print(df_google.Embarked.unique())

[0 1]
[3 1 2]
['male' 'female']
[1 0 3 4 2 5 8]
[0 1 2 5 3 4 6]
['S' 'C' 'Q' nan]


In [24]:
df = acquire.get_titanic_data()

In [26]:
df = acquire.get_iris_data()