In [74]:
import pandas as pd
import numpy as np
from pydataset import data
import acquire

import prepare
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from scipy import stats

from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import classification_report

|               | actual cat | actual dog |
|:------------  |-----------:|-----------:|
| predicted cat |         34 |          7 |
| predicted dog |         13 |         46 |

In [7]:
TP = 34
TN = 46
FP = 7
FN = 13

In [8]:
Recall = TP/(TP+FN)
Recall

0.723404255319149

In [9]:
precision = TP/(TP+FP)
precision

0.8292682926829268

In [10]:
accuracy = (TP+TN)/(TP+TN+FP+FN)
accuracy

0.8

## 2. You are working as a datascientist working for Codeup Cody Creator (C3 for short), a rubber-duck manufacturing plant.

## Unfortunately, some of the rubber ducks that are produced will have defects. Your team has built several models that try to predict those defects, and the data from their predictions can be found here (c3.csv).

### Use the predictions dataset and pandas to help answer the following questions:

### An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

In [11]:
df = pd.read_csv('c3.csv')

In [12]:
df

actual     model1     model2     model3
0    No Defect  No Defect     Defect  No Defect
1    No Defect  No Defect     Defect     Defect
2    No Defect  No Defect     Defect  No Defect
3    No Defect     Defect     Defect     Defect
4    No Defect  No Defect     Defect  No Defect
..         ...        ...        ...        ...
195  No Defect  No Defect     Defect     Defect
196     Defect     Defect  No Defect  No Defect
197  No Defect  No Defect  No Defect  No Defect
198  No Defect  No Defect     Defect     Defect
199  No Defect  No Defect  No Defect     Defect

[200 rows x 4 columns]

## It would be useful to have a model with high recall (sensitivity)

In [19]:
subset1 = df[df.actual == 'Defect']

In [20]:
(subset1.actual == subset1.model1).mean()

0.5

In [21]:
(subset1.actual == subset1.model2).mean()

0.5625

In [22]:
(subset1.actual == subset1.model3).mean()

0.8125

### Model3 has highest recall, this would be the best choice
***

### Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. They need you to predict which ducks will have defects, but tell you the really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?

### Precision would be appropriate matrix here


In [23]:
subset1 = df[df.model1 == 'Defect']
subset2 = df[df.model2 == 'Defect']
subset2 = df[df.model3 == 'Defect']

In [24]:
(subset1.actual == subset1.model1).mean()

0.8

In [25]:
(subset2.actual == subset2.model2).mean()

0.6060606060606061

In [26]:
(subset3.actual == subset3.model3).mean()

0.8125

### Model 3 has highest precision
***

### You are working as a data scientist for Gives You Paws ™, a subscription based service that shows you cute pictures of dogs or cats (or both for an additional fee).

### At Gives You Paws, anyone can upload pictures of their cats or dogs. The photos are then put through a two step process. First an automated algorithm tags pictures as either a cat or a dog (Phase I). Next, the photos that have been initially identified are put through another round of review, possibly with some human oversight, before being presented to the users (Phase II).

### Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) and answer the following questions:

### In terms of accuracy, how do the various models compare to the baseline model? Are any of the models better than the baseline?

In [33]:
df = pd.read_csv('gives_you_paws.csv')

In [34]:
df.describe()

actual model1 model2 model3 model4
count    5000   5000   5000   5000   5000
unique      2      2      2      2      2
top       dog    dog    cat    dog    dog
freq     3254   2937   3212   2508   4253

Dog is the most common class. So we will use it as baseline

In [35]:
df['baseline'] = 'dog'

In [36]:
df.head(2)

actual model1 model2 model3 model4 baseline
0    cat    cat    dog    cat    dog      dog
1    dog    dog    cat    cat    dog      dog

In [37]:
accuracy1 = (df.actual == df.model1).mean()
accuracy1

0.8074

In [38]:
accuracy2 = (df.actual == df.model2).mean()
accuracy2

0.6304

In [39]:
accuracy3 = (df.actual == df.model3).mean()
accuracy3

0.5096

In [40]:
accuracy4 = (df.actual == df.model4).mean()
accuracy4

0.7426

In [41]:
accuracy_bl = (df.actual == df.baseline).mean()
accuracy_bl

0.6508

## model 1 and 4 are better than baseline

### Suppose you are working on a team that solely deals with dog pictures. Which of these models would you recomend for Phase I? For Phase II?

#### For phase 1, we should choose a model with highest recall/sensitivity and specifity

In [42]:
subset1 = df[df.actual == 'dog']
subset1.head()

actual model1 model2 model3 model4 baseline
1    dog    dog    cat    cat    dog      dog
2    dog    cat    cat    cat    dog      dog
3    dog    dog    dog    cat    dog      dog
5    dog    dog    dog    dog    dog      dog
8    dog    dog    cat    dog    dog      dog

In [43]:
(subset1.actual == subset1.model1).mean()

0.803318992009834

In [44]:
(subset1.actual == subset1.model2).mean()

0.49078057775046097

In [45]:
(subset1.actual == subset1.model3).mean()

0.5086047940995697

In [46]:
(subset1.actual == subset1.model4).mean()

0.9557467732022127

In [47]:
(subset1.actual == subset1.baseline).mean()

1.0

### For phase 2 we should choose model which has high precision

In [53]:
subset1 = df[df.model1 == 'dog']
subset2 = df[df.model2 == 'dog']
subset3 = df[df.model3 == 'dog']
subset4 = df[df.model4 == 'dog']
subset_bl = df[df.baseline == 'dog']

In [56]:
(subset1.actual == subset1.model1).mean()

0.8900238338440586

In [58]:
(subset2.actual == subset2.model2).mean()

0.8931767337807607

In [59]:
(subset3.actual == subset3.model3).mean()

0.6598883572567783

In [60]:
(subset4.actual == subset4.model4).mean()

0.7312485304490948

In [61]:
(subset_bl.actual == subset_bl.baseline).mean()

0.6508

### Model 2 has best precision
***

Suppose you are working on a team that solely deals with cat pictures. Which of these models would you recomend for Phase I? For Phase II?

In [62]:
subset1 = df[df.actual == 'cat']

In [63]:
(subset1.actual == subset1.model1).mean()

0.8150057273768614

In [64]:
(subset1.actual == subset1.model2).mean()

0.8906071019473081

In [65]:
(subset1.actual == subset1.model3).mean()

0.5114547537227949

In [66]:
(subset1.actual == subset1.model4).mean()

0.34536082474226804

### model 2 has highest sensitivity so best for phase1
***

In [67]:
# For phase 2, lets calculation precision
subset1 = df[df.model1 == 'cat']
subset2 = df[df.model2 == 'cat']
subset3 = df[df.model3 == 'cat']
subset4 = df[df.model4 == 'cat']

In [68]:
(subset1.actual == subset1.model1).mean()

0.6897721764420747

In [69]:
(subset2.actual == subset2.model2).mean()

0.4841220423412204

In [70]:
(subset3.actual == subset3.model3).mean()

0.358346709470305

In [71]:
(subset4.actual == subset4.model4).mean()

0.8072289156626506

### model 4 has highest precision, hence best for phase 2(cat)
***

## Follow the links below to read the documentation about each function, then apply those functions to the data from the previous problem.

In [83]:
precision_score(df.actual, df.model1, average = None)

array([0.68977218, 0.89002383])

In [84]:
precision_score(df.actual, df.model2, average = None)

array([0.48412204, 0.89317673])

In [85]:
precision_score(df.actual, df.model3, average = None)

array([0.35834671, 0.65988836])

In [86]:
precision_score(df.actual, df.model4, average = None)

array([0.80722892, 0.73124853])

In [87]:
recall_score(df.actual, df.model1, average = None)

array([0.81500573, 0.80331899])

In [88]:
recall_score(df.actual, df.model2, average = None)

array([0.8906071 , 0.49078058])

In [89]:
recall_score(df.actual, df.model3, average = None)

array([0.51145475, 0.50860479])

In [90]:
recall_score(df.actual, df.model4, average = None)

array([0.34536082, 0.95574677])